name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      greeting:
        description: 'Greeting parameter'
        required: true
        default: 'hello'

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Say hello
        run: echo "The greeting is ${{ github.event.inputs.greeting }}"